# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: large_message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13large_message.proto\x12\x0clargemessage\"C\n\x0cLargeMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"i\n\x14LargeMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x03\x12\x11\n\tdata_size\x18\x04 \x01(\x03\"%\n\rHealthRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"3\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\xba\x01\n\x13LargeMessageService\x12W\n\x13ProcessLargeMessage\x12\x1a.largemessage.LargeMessage\x1a\".largemessage.LargeMessageResponse\"\x00\x12J\n\x0bHealthCheck\x12\x1b.largemessage.HealthRequest\x1a\x1c.largemessage.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'large_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LARGEMESSAGE']._serialized_start=37
  _globals['_LARGEMESSAGE']._serialized_end=104
  _globals['_LARGEMESSAGERESPONSE']._serialized_start=106
  _globals['_LARGEMESSAGERESPONSE']._serialized_end=211
  _globals['_HEALTHREQUEST']._serialized_start=213
  _globals['_HEALTHREQUEST']._serialized_end=250
  _globals['_HEALTHRESPONSE']._serialized_start=252
  _globals['_HEALTHRESPONSE']._serialized_end=303
  _globals['_LARGEMESSAGESERVICE']._serialized_start=306
  _globals['_LARGEMESSAGESERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
